sbatch meta_train_mlp_morefeat.slurm 1
sbatch meta_train_mlp_morefeat.slurm 2
sbatch meta_train_mlp_morefeat.slurm 4
sbatch meta_train_mlp_morefeat.slurm 8
sbatch meta_train_mlp_morefeat.slurm 16
sbatch meta_train_mlp_morefeat.slurm